name: "Create Dependency Update PR"
description: "Creates a PR for dependency updates"

inputs:
  token:
    description: "GitHub token"
    required: true
  package-name:
    description: "Package being updated"
    required: true
  version:
    description: "New version"
    required: true
  target-repo:
    description: "Target repository"
    required: true

outputs:
  pr-url:
    description: "URL of the created pull request"
    value: ${{ steps.create-pr.outputs.pull-request-url }}
  pr-created:
    description: "Whether a PR was created"
    value: ${{ steps.create-pr.outputs.pull-request-created }}

runs:
  using: "composite"
  steps:
    - name: Checkout ${{ inputs.target-repo }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.target-repo }}
        token: ${{ inputs.token }}
        ref: main
        fetch-depth: 1

    - id: create-pr
      uses: peter-evans/create-pull-request@v7
      with:
        draft: true
        token: ${{ inputs.token }}
        branch: 🏴‍☠️/${{ inputs.package-name }}/${{ inputs.version }}
        base: main
        title: "bump ${{ inputs.package-name }} to ${{ inputs.version }}"
        body: |
          Automatically updating ${{ inputs.package-name }} in `${{ inputs.target-repo }}` to version ${{ inputs.version }}.
          The repo for this package is: (${{ github.repositoryUrl }}).
        labels: "dependencies, automation"
        add-paths: |
          pnpm-lock.yaml
          yarn.lock
          package.json
          **/package.json

    - name: Check PR creation
      shell: bash
      run: |
        if [ "${{ steps.create-pr.outputs.pull-request-created }}" != "true" ]; then
          echo "No PR was created. This could mean there were no changes to commit."
          exit 1
        fi
        echo "PR created successfully: ${{ steps.create-pr.outputs.pull-request-url }}"
